import { mount } from '@vue/test-utils'
import { createMemoryHistory, createRouter } from 'vue-router'
import { describe, expect, it } from 'vitest'
import LoginView from './LoginView.vue'
import { rememberDingTalkFailure } from '../auth'

describe('LoginView',()=>{
  it('shows all five fixed roles and the streamlined password form',async()=>{const router=createRouter({history:createMemoryHistory(),routes:[{path:'/',component:LoginView}]});await router.push('/');await router.isReady();const wrapper=mount(LoginView,{global:{plugins:[router]}});for(const role of ['超管','运营','观察员','化妆师','主播'])expect(wrapper.text()).toContain(role);expect(wrapper.find('.password-login h2').exists()).toBe(false);expect(wrapper.find('input[autocomplete="username"]').exists()).toBe(true);expect(wrapper.find('input[autocomplete="current-password"]').exists()).toBe(true);expect(wrapper.text()).not.toContain('化妆预约')})
  it('enables password login only for 6-12 character alphanumeric accounts and passwords',async()=>{const router=createRouter({history:createMemoryHistory(),routes:[{path:'/',component:LoginView}]});await router.push('/');await router.isReady();const wrapper=mount(LoginView,{global:{plugins:[router]}});const inputs=wrapper.findAll('.password-login input'),button=wrapper.find('.login-submit');await inputs[0].setValue('12345');await inputs[1].setValue('123456');expect(button.attributes('disabled')).toBeDefined();await inputs[0].setValue(' Abc123 ');expect(button.attributes('disabled')).toBeUndefined();await inputs[0].setValue('abc_123');expect(button.attributes('disabled')).toBeDefined();await inputs[0].setValue('abcdefghijklm');expect(button.attributes('disabled')).toBeDefined();await inputs[0].setValue('Abc123');await inputs[1].setValue('12345');expect(button.attributes('disabled')).toBeDefined();await inputs[1].setValue('abcdefghijklm');expect(button.attributes('disabled')).toBeDefined()})
  it('shows stored recovery details without placing diagnostics in the URL',async()=>{sessionStorage.clear();const details=rememberDingTalkFailure(Object.assign(new Error('private'),{code:'DINGTALK_AUTH_TIMEOUT',traceId:'server-trace-1234'}));const router=createRouter({history:createMemoryHistory(),routes:[{path:'/login',component:LoginView}]});await router.push('/login?redirect=/booking');await router.isReady();const wrapper=mount(LoginView,{global:{plugins:[router]}});expect(router.currentRoute.value.fullPath).toBe('/login?redirect=/booking');expect(router.currentRoute.value.fullPath).not.toMatch(/diagnostic|trace|error/i);expect(wrapper.get('.dingtalk-login').text()).toBe('重新免登');expect(wrapper.get('.dingtalk-diagnostic').text()).toContain('DINGTALK_AUTH_TIMEOUT');expect(wrapper.get('.dingtalk-diagnostic').text()).toContain(details.diagnosticId);expect(wrapper.get('.dingtalk-diagnostic').text()).toContain('server-trace-1234');expect(wrapper.text()).not.toMatch(/authCode|Token|Secret|stack|private/)})
})
