package com.jiabei.cloud.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.jiabei.cloud.security.CurrentUser;
import com.jiabei.cloud.web.BusinessException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.http.HttpStatus;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class AdminResourceService {
  private final JdbcTemplate jdbc;private final ObjectMapper json;private final CardRefreshService cards;
  public AdminResourceService(JdbcTemplate jdbc,ObjectMapper json){this(jdbc,json,null);}
  @Autowired public AdminResourceService(JdbcTemplate jdbc,ObjectMapper json,CardRefreshService cards){this.jdbc=jdbc;this.json=json;this.cards=cards;}
  public List<Map<String,Object>> makeupArtists(CurrentUser actor){String sql="SELECT id,name,avatar_url,work_days,work_start,work_end,schedule_enabled,is_attending,is_active,version,updated_at FROM makeup_artist";Object[] args={};if(actor.role()==CurrentUser.Role.MAKEUP){sql+=" WHERE id=?";args=new Object[]{actor.makeupArtistId()};}sql+=" ORDER BY CASE WHEN NOT is_active THEN 2 WHEN NOT is_attending THEN 1 ELSE 0 END,updated_at DESC,id";return jdbc.query(sql,(rs,n)->{Map<String,Object> m=new LinkedHashMap<>();m.put("id",rs.getObject(1,UUID.class));m.put("name",rs.getString(2));m.put("avatarUrl",value(rs.getString(3)));m.put("workDays",workDays(rs.getString(4)));m.put("workStart",rs.getObject(5,LocalTime.class));m.put("workEnd",rs.getObject(6,LocalTime.class));m.put("scheduleEnabled",rs.getBoolean(7));m.put("attending",rs.getBoolean(8));m.put("active",rs.getBoolean(9));m.put("version",rs.getInt(10));m.put("updatedAt",rs.getObject(11));return m;},args);}
  public List<Map<String,Object>> teams(){return jdbc.query("SELECT id,name,logo_url,is_active,version,updated_at,team_no FROM team ORDER BY is_active DESC,updated_at DESC,id",(rs,n)->{Map<String,Object> m=new LinkedHashMap<>();m.put("id",rs.getObject(1,UUID.class));m.put("name",rs.getString(2));m.put("logoUrl",value(rs.getString(3)));m.put("active",rs.getBoolean(4));m.put("version",rs.getInt(5));m.put("updatedAt",rs.getObject(6));m.put("teamNo",rs.getObject(7,Integer.class));return m;});}
  public List<Map<String,Object>> streamers(){return jdbc.query("SELECT coalesce(dingtalk_user_id,username),nickname,is_attending,dingtalk_user_id IS NOT NULL FROM app_user WHERE role='STREAMER' AND is_active ORDER BY created_at",(rs,n)->Map.of("userId",rs.getString(1),"nickname",rs.getString(2),"attending",rs.getBoolean(3),"dingTalkBound",rs.getBoolean(4)));}
  public Map<String,Object> setting(){return jdbc.queryForObject("SELECT boolean_value,version,updated_at FROM system_setting WHERE key='SYSTEM_ENABLED'",(rs,n)->Map.of("enabled",rs.getBoolean(1),"version",rs.getInt(2),"updatedAt",rs.getObject(3)));}
  @Transactional public Map<String,Object> updateSetting(CurrentUser actor,boolean enabled,int version,String trace){requireAdmin(actor);int n=jdbc.update("UPDATE system_setting SET boolean_value=?,version=version+1,updated_by_user_id=?,updated_at=now() WHERE key='SYSTEM_ENABLED' AND version=?",enabled,actor.id(),version);if(n==0)throw versionConflict();audit(UUID.nameUUIDFromBytes("SYSTEM_ENABLED".getBytes()),"SYSTEM_SETTING","UPDATE",actor,null,Map.of("enabled",!enabled),Map.of("enabled",enabled),trace);return setting();}
  @Transactional public Map<String,Object> createMakeupArtist(CurrentUser actor,MakeupArtistCreate p,String trace){requireAdmin(actor);List<Integer> workDays=p.workDays()==null?List.of():p.workDays();LocalTime start=p.workStart()==null?LocalTime.of(8,0):p.workStart(),end=p.workEnd()==null?LocalTime.of(20,0):p.workEnd();if(!p.scheduleEnabled()&&!validTimes(start,end)){start=LocalTime.of(8,0);end=LocalTime.of(20,0);}validateMakeupArtist(p.name(),workDays,start,end,p.scheduleEnabled());UUID id=UUID.randomUUID();jdbc.update("INSERT INTO makeup_artist(id,name,avatar_url,work_days,work_start,work_end,schedule_enabled,is_attending,is_active) VALUES (?,?,?,?,?,?,?,?,?)",id,p.name().trim(),blank(p.avatarUrl()),days(workDays),start,end,p.scheduleEnabled(),p.attending(),p.active());Map<String,Object> after=new LinkedHashMap<>();after.put("name",p.name().trim());after.put("workDays",workDays);after.put("workStart",start);after.put("workEnd",end);after.put("scheduleEnabled",p.scheduleEnabled());after.put("attending",p.attending());after.put("active",p.active());audit(id,"MAKEUP_ARTIST","CREATE",actor,p.reason(),Map.of(),after,trace);return makeupArtists(actor).stream().filter(x->id.equals(x.get("id"))).findFirst().orElseThrow();}
  @Transactional public Map<String,Object> updateMakeupArtist(CurrentUser actor,UUID id,MakeupArtistPatch p,String trace){requireAdmin(actor);Map<String,Object> before=lockMakeupArtist(id);if((int)before.get("version")!=p.version())throw versionConflict();String name=p.name()==null?(String)before.get("name"):p.name().trim();@SuppressWarnings("unchecked") List<Integer> workDays=p.workDays()==null?(List<Integer>)before.get("workDays"):p.workDays();boolean scheduleEnabled=p.scheduleEnabled()==null?(boolean)before.get("scheduleEnabled"):p.scheduleEnabled();LocalTime start=p.workStart()==null?(LocalTime)before.get("workStart"):p.workStart(),end=p.workEnd()==null?(LocalTime)before.get("workEnd"):p.workEnd();if(!scheduleEnabled){start=(LocalTime)before.get("workStart");end=(LocalTime)before.get("workEnd");}validateMakeupArtist(name,workDays,start,end,scheduleEnabled);boolean active=p.active()==null?(boolean)before.get("active"):p.active(),attending=p.attending()==null?(boolean)before.get("attending"):p.attending();String avatar=p.avatarUrl()==null?(String)before.get("avatarUrl"):blank(p.avatarUrl());List<LocalDate> affected=jdbc.query("SELECT DISTINCT booking_date FROM appointment WHERE makeup_artist_id=?",(rs,n)->rs.getObject(1,LocalDate.class),id);jdbc.update("UPDATE makeup_artist SET name=?,avatar_url=?,work_days=?,work_start=?,work_end=?,schedule_enabled=?,is_attending=?,is_active=?,version=version+1,updated_at=now() WHERE id=?",name,avatar,days(workDays),start,end,scheduleEnabled,attending,active,id);if(!name.equals(before.get("name"))){jdbc.update("UPDATE app_user SET nickname=?,version=version+1,updated_at=now() WHERE makeup_artist_id=? AND nickname<>?",name,id,name);int changed=jdbc.update("UPDATE appointment SET makeup_artist_name_snapshot=?,updated_at=now() WHERE makeup_artist_id=? AND makeup_artist_name_snapshot<>?",name,id,name);if(changed>0&&cards!=null)cards.refreshExistingDates(affected);}Map<String,Object> after=new LinkedHashMap<>();after.put("name",name);after.put("avatarUrl",avatar);after.put("workDays",workDays);after.put("workStart",start);after.put("workEnd",end);after.put("scheduleEnabled",scheduleEnabled);after.put("attending",attending);after.put("active",active);audit(id,"MAKEUP_ARTIST","UPDATE",actor,p.reason(),before,after,trace);return makeupArtists(actor).stream().filter(x->id.equals(x.get("id"))).findFirst().orElseThrow();}
  @Transactional public Map<String,Object> createTeam(CurrentUser actor,TeamCreate p,String trace){requireAdmin(actor);if(p.name()==null||p.name().isBlank())throw invalid("团队名称不能为空。");UUID id=UUID.randomUUID();try{jdbc.update("INSERT INTO team(id,name,logo_url,is_active) VALUES (?,?,?,?)",id,p.name().trim(),blank(p.logoUrl()),p.active());}catch(DataIntegrityViolationException e){throw teamNameExists();}audit(id,"TEAM","CREATE",actor,p.reason(),Map.of(),Map.of("name",p.name().trim(),"active",p.active()),trace);return teams().stream().filter(x->id.equals(x.get("id"))).findFirst().orElseThrow();}
  @Transactional public Map<String,Object> updateTeam(CurrentUser actor,UUID id,TeamPatch p,String trace){requireAdmin(actor);Map<String,Object> before=lockTeam(id);if((int)before.get("version")!=p.version())throw versionConflict();String name=p.name()==null?(String)before.get("name"):p.name().trim();if(name.isBlank())throw invalid("团队名称不能为空。");String logo=p.logoUrl()==null?(String)before.get("logoUrl"):blank(p.logoUrl());boolean active=p.active()==null?(boolean)before.get("active"):p.active();List<LocalDate> affected=jdbc.query("SELECT DISTINCT booking_date FROM appointment WHERE team_id=?",(rs,n)->rs.getObject(1,LocalDate.class),id);try{jdbc.update("UPDATE team SET name=?,logo_url=?,is_active=?,version=version+1,updated_at=now() WHERE id=?",name,logo,active,id);}catch(DataIntegrityViolationException e){throw teamNameExists();}if(!name.equals(before.get("name"))){int changed=jdbc.update("UPDATE appointment SET team_name_snapshot=?,updated_at=now() WHERE team_id=? AND team_name_snapshot<>?",name,id,name);if(changed>0&&cards!=null)cards.refreshExistingDates(affected);}Map<String,Object> after=Map.of("name",name,"logoUrl",value(logo),"active",active);audit(id,"TEAM","UPDATE",actor,p.reason(),before,after,trace);return teams().stream().filter(x->id.equals(x.get("id"))).findFirst().orElseThrow();}
  public List<Map<String,Object>> auditLogs(String entityType,UUID entityId){return jdbc.query("SELECT action,actor_name_snapshot,reason,before_data::text,after_data::text,created_at FROM audit_log WHERE entity_type=? AND entity_id=? ORDER BY created_at DESC",(rs,n)->{Map<String,Object> m=new LinkedHashMap<>();m.put("action",rs.getString(1));m.put("actorName",rs.getString(2));m.put("reason",rs.getString(3));m.put("before",rs.getString(4));m.put("after",rs.getString(5));m.put("createdAt",rs.getObject(6));return m;},entityType,entityId);}
  private Map<String,Object> lockMakeupArtist(UUID id){List<Map<String,Object>> rows=jdbc.query("SELECT id,name,avatar_url,work_days,work_start,work_end,schedule_enabled,is_attending,is_active,version FROM makeup_artist WHERE id=? FOR UPDATE",(rs,n)->{Map<String,Object> m=new LinkedHashMap<>();m.put("id",rs.getObject(1,UUID.class));m.put("name",rs.getString(2));m.put("avatarUrl",value(rs.getString(3)));m.put("workDays",workDays(rs.getString(4)));m.put("workStart",rs.getObject(5,LocalTime.class));m.put("workEnd",rs.getObject(6,LocalTime.class));m.put("scheduleEnabled",rs.getBoolean(7));m.put("attending",rs.getBoolean(8));m.put("active",rs.getBoolean(9));m.put("version",rs.getInt(10));return m;},id);if(rows.isEmpty())throw new BusinessException(HttpStatus.NOT_FOUND,"MAKEUP_ARTIST_NOT_FOUND","化妆师不存在。");return rows.getFirst();}
  private Map<String,Object> lockTeam(UUID id){List<Map<String,Object>> rows=jdbc.query("SELECT id,name,logo_url,is_active,version FROM team WHERE id=? FOR UPDATE",(rs,n)->{Map<String,Object> m=new LinkedHashMap<>();m.put("id",rs.getObject(1,UUID.class));m.put("name",rs.getString(2));m.put("logoUrl",value(rs.getString(3)));m.put("active",rs.getBoolean(4));m.put("version",rs.getInt(5));return m;},id);if(rows.isEmpty())throw new BusinessException(HttpStatus.NOT_FOUND,"TEAM_NOT_FOUND","团队不存在。");return rows.getFirst();}
  private void validateMakeupArtist(String name,List<Integer> workDays,LocalTime start,LocalTime end,boolean scheduleEnabled){if(name==null||name.isBlank())throw invalid("化妆师名称不能为空。");if(workDays==null||workDays.stream().anyMatch(d->d<1||d>7))throw invalid("工作日无效。");if(scheduleEnabled&&workDays.isEmpty())throw invalid("请至少选择一个工作日。");if(scheduleEnabled&&(start==null||end==null||!end.isAfter(start)))throw invalid("上班时间必须早于下班时间。");if(scheduleEnabled&&(start.getMinute()%10!=0||end.getMinute()%10!=0))throw invalid("请选择10分钟刻度的工作时间。");}
  private boolean validTimes(LocalTime start,LocalTime end){return start!=null&&end!=null&&end.isAfter(start)&&start.getMinute()%10==0&&end.getMinute()%10==0;}
  private List<Integer> workDays(String raw){return raw==null||raw.isBlank()?List.of():Arrays.stream(raw.split(",")).map(Integer::valueOf).toList();}
  private String days(List<Integer> values){return values==null?"":values.stream().distinct().sorted().map(String::valueOf).reduce((a,b)->a+","+b).orElse("");}
  private void requireAdmin(CurrentUser actor){if(!actor.isAdministrator())throw BusinessException.forbidden();}
  private BusinessException invalid(String message){return new BusinessException(HttpStatus.UNPROCESSABLE_ENTITY,"RESOURCE_DATA_INVALID",message);}private BusinessException versionConflict(){return new BusinessException(HttpStatus.CONFLICT,"VERSION_CONFLICT","数据已变化，请刷新后重试。");}
  private BusinessException teamNameExists(){return new BusinessException(HttpStatus.CONFLICT,"TEAM_NAME_EXISTS","团队名称已存在，请使用其他名称。");}
  private void audit(UUID entity,String type,String action,CurrentUser actor,String reason,Object before,Object after,String trace){jdbc.update("INSERT INTO audit_log(id,entity_type,entity_id,action,actor_user_id,actor_identity_snapshot,actor_name_snapshot,reason,before_data,after_data,trace_id) VALUES (?,?,?,?,?,?,?,?,CAST(? AS jsonb),CAST(? AS jsonb),?)",UUID.randomUUID(),type,entity,action,actor.id(),actor.loginId(),actor.nickname(),blank(reason),toJson(before),toJson(after),trace);}
  private String blank(String v){return v==null||v.isBlank()?null:v.trim();}private String value(String v){return v==null?"":v;}private String toJson(Object o){try{return json.writeValueAsString(o);}catch(JsonProcessingException e){throw new IllegalStateException(e);}}
  public record MakeupArtistCreate(String name,String avatarUrl,List<Integer> workDays,LocalTime workStart,LocalTime workEnd,boolean scheduleEnabled,boolean active,boolean attending,String reason){}
  public record MakeupArtistPatch(String name,String avatarUrl,List<Integer> workDays,LocalTime workStart,LocalTime workEnd,Boolean scheduleEnabled,Boolean active,Boolean attending,int version,String reason){}
  public record TeamCreate(String name,String logoUrl,boolean active,String reason){}public record TeamPatch(String name,String logoUrl,Boolean active,int version,String reason){}
}
