import { expect, test } from '@playwright/test'

const appointment={id:'a1',bookingDate:'2026-09-07',startTime:'19:00',streamerName:'玲玲',makeupArtistName:'小贝老师',teamName:'星河一团',makeupArtistId:'t1',teamId:'g1',status:'ACTIVE',attendanceStatus:'PENDING',conflictOverride:true,version:0}
async function mockAdmin(page:any,role='SUPER_ADMIN'){
  const accountRows=[
    {id:'u1',nickname:'Admin',role:'SUPER_ADMIN',active:true,version:0},
    {id:'s1',username:'JB2609070001',dingTalkUserId:'streamer01',dingTalkUsername:'玲玲',nickname:'玲玲',role:'STREAMER',active:true,attending:false,canModifyAppointments:false,canCancelAppointments:false,lastLoginAt:'2026-09-08T11:00:00+08:00',version:0},
    {id:'m1',makeupArtistId:'t1',dingTalkUserId:'makeup01',dingTalkUsername:'小贝老师',nickname:'小贝老师',role:'MAKEUP',active:true,attending:true,canCreateAppointments:true,lastLoginAt:'2026-09-08T11:00:00+08:00',version:0},
    {id:'o1',dingTalkUserId:'operator01',dingTalkUsername:'运营一号',nickname:'运营一号',role:'OPERATOR',active:true,canCreateAppointments:true,version:0},
    ...Array.from({length:5},(_,index)=>({id:`s${index+2}`,dingTalkUserId:`extra${index+2}`,dingTalkUsername:`主播${index+2}`,nickname:`主播${index+2}`,role:'STREAMER',active:true,attending:true,version:0})),
  ]
  await page.route('**/api/v1/me',r=>r.fulfill({json:{success:true,data:{userId:'u1',nickname:role==='OBSERVER'?'观察员一号':'Admin',role,canModifyAppointments:true,canCancelAppointments:true,canCreateAppointments:true,csrfToken:'csrf'}}}))
  await page.route('**/api/v1/auth/mock-login',r=>r.fulfill({json:{success:true,data:{userId:r.request().postDataJSON().userId,nickname:'切换账号',role:'OBSERVER',canCreateAppointments:false,csrfToken:'csrf-next'}}}))
  await page.route('**/api/v1/admin/appointments/schedule-card',r=>r.fulfill({json:{success:true,data:{queued:true}}}))
  await page.route('**/api/v1/admin/appointments/export**',r=>r.fulfill({status:200,headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':"attachment; filename*=UTF-8''records.xlsx"},body:'xlsx'}))
  await page.route('**/api/v1/admin/appointments**',r=>r.fulfill({json:{success:true,data:{items:[appointment],total:31,page:1,size:30,totalPages:2}}}))
  await page.route('**/api/v1/admin/appointments/schedule-card/status',r=>r.fulfill({json:{success:true,data:{dates:[{key:'today',bookingDate:'2026-09-08',hasSuccessfulDelivery:false,firstDeliveredAt:null},{key:'tomorrow',bookingDate:'2026-09-09',hasSuccessfulDelivery:true,firstDeliveredAt:'2026-09-08T10:00:00+08:00'}]}}}))
  await page.route('**/api/v1/admin/appointments/options**',r=>r.fulfill({json:{success:true,data:{streamers:[{userId:'s1',nickname:'玲玲'}],makeupArtists:[{id:'t1',name:'小贝老师',active:true,attending:true}],teams:[{id:'g1',name:'星河一团',active:true}]}}}))
  await page.route('**/api/v1/admin/appointments/availability**',r=>r.fulfill({json:{success:true,data:{slots:[{time:'08:00',available:true},{time:'08:10',available:true},{time:'09:00',available:true}],conflictAllowed:true}}}))
  await page.route('**/api/v1/admin/analytics**',r=>r.fulfill({json:{success:true,data:{startDate:'2026-08-10',endDate:'2026-09-08',summary:{total:8,active:6,cancelled:2,arrived:3,late:2,notArrived:1,modifications:4,cancellations:2,averageEarlyMinutes:6,averageLateMinutes:9},daily:[{date:'2026-09-07',total:3,active:2,cancelled:1,arrived:1,late:1,notArrived:0},{date:'2026-09-08',total:5,active:4,cancelled:1,arrived:2,late:1,notArrived:1}],streamers:[{streamerId:'s1',streamerName:'玲玲',appointments:5,late:1,notArrived:1,modifications:2,cancellations:1}],makeupArtists:[{makeupArtistId:'t1',makeupArtistName:'小贝老师',activeAppointments:6}],teams:[{teamId:'g1',teamName:'星河一团',activeAppointments:6}]}}}))
  await page.route('**/api/v1/availability**',r=>r.fulfill({json:{success:true,data:{slots:[{time:'08:00',available:true},{time:'08:10',available:true},{time:'09:00',available:true}],conflictAllowed:true}}}))
  await page.route('**/api/v1/admin/makeup-artists',r=>r.fulfill({json:{success:true,data:[{id:'t1',name:'小贝老师',workDays:[1,2,3,4,5,6,7],workStart:'08:00',workEnd:'20:00',scheduleEnabled:true,active:true,attending:true,version:0},{id:'t2',name:'休息老师',workDays:[1],workStart:'08:00',workEnd:'20:00',scheduleEnabled:true,active:true,attending:false,version:0}]}}))
  await page.route('**/api/v1/admin/teams',r=>r.fulfill({json:{success:true,data:[{id:'g1',name:'星河一团',active:true,version:0},{id:'g2',name:'停用测试团',active:false,version:0}]}}))
  await page.route('**/api/v1/admin/accounts',r=>r.fulfill({json:{success:true,data:accountRows}}))
  await page.route('**/api/v1/admin/dingtalk-employees**',r=>r.fulfill({json:{success:true,data:[{dingTalkUserId:'user123456',dingTalkUsername:'张三',label:'张三 @user123456'}]}}))
  await page.route('**/api/v1/admin/streamers',r=>r.fulfill({json:{success:true,data:[{userId:'s1',nickname:'玲玲'}]}}))
  await page.route('**/api/v1/admin/system-setting',r=>r.fulfill({json:{success:true,data:{enabled:true,version:0}}}))
  return {accountRows}
}

test('login labels and DingTalk outside-client warning',async({page})=>{
  await page.route('**/api/v1/me',r=>r.fulfill({status:401,json:{success:false,error:{code:'UNAUTHORIZED',message:'未登录'}}}))
  await page.goto('/login')
  await expect(page.getByText('化妆师',{exact:true})).toBeVisible()
  await expect(page.getByRole('heading',{name:'账号登录',exact:true})).toBeVisible()
  const login=page.getByRole('button',{name:'登录',exact:true}),inputs=page.locator('.password-login input')
  await inputs.nth(0).fill('12345');await inputs.nth(1).fill('123456');await expect(login).toBeDisabled()
  await inputs.nth(0).fill(' 123456 ');await expect(login).toBeEnabled()
  await page.getByRole('button',{name:'钉钉免登'}).click()
  await expect(page.locator('.app-toast-error')).toContainText('免登异常，请联系管理员')
})

test('root resolves by role and admin tab survives refresh',async({page})=>{
  await mockAdmin(page)
  await page.goto('/')
  await expect(page).toHaveURL(/\/admin\?tab=appointments$/)
  await page.locator('button:visible').filter({hasText:/^设置$/}).click()
  await expect(page).toHaveURL(/tab=settings/)
  await expect(page.getByRole('heading',{name:'系统入口'})).toBeVisible()
  await page.reload()
  await expect(page).toHaveURL(/tab=settings/)
  await expect(page.getByRole('heading',{name:'系统入口'})).toBeVisible()
})

test('password form submits with Enter',async({page})=>{
  await mockAdmin(page)
  await page.route('**/api/v1/me',r=>r.fulfill({status:401,json:{success:false,error:{code:'UNAUTHORIZED',message:'未登录'}}}))
  await page.route('**/api/v1/auth/password-login',r=>r.fulfill({json:{success:true,data:{userId:'u1',nickname:'Admin',role:'SUPER_ADMIN',canModifyAppointments:true,canCancelAppointments:true,canCreateAppointments:true,csrfToken:'csrf'}}}))
  await page.goto('/login')
  const inputs=page.locator('.password-login input')
  await inputs.nth(0).fill('admin01');await inputs.nth(1).fill('secret12');await inputs.nth(1).press('Enter')
  await expect(page).toHaveURL(/\/admin\?tab=appointments$/)
})

test('login controls and compact admin header fit 320 to 430 pixels',async({page})=>{
  await page.route('**/api/v1/me',r=>r.fulfill({status:401,json:{success:false,error:{code:'UNAUTHORIZED',message:'未登录'}}}))
  await page.goto('/login')
  for(const width of [320,390,430]){
    await page.setViewportSize({width,height:820})
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)
    const eye=await page.getByRole('button',{name:'显示密码'}).boundingBox()
    expect(eye?.width).toBe(44);expect(eye?.height).toBe(44)
  }
  await mockAdmin(page);await page.goto('/admin?tab=appointments');await page.setViewportSize({width:430,height:820})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)
  expect(await page.locator('.admin-sidebar').evaluate(element=>Math.round(element.getBoundingClientRect().height))).toBe(56)
})

test('streamer schedule, premium appointment and avatar logout',async({page})=>{
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(new Date())
  const active={...appointment,bookingDate:today,startTime:'13:30',attendanceStatus:'LATE'}
  await page.route('**/api/v1/me',r=>r.fulfill({json:{success:true,data:{userId:'s1',nickname:'玲玲',role:'STREAMER',csrfToken:'csrf'}}}))
  await page.route('**/api/v1/booking-context**',r=>r.fulfill({json:{success:true,data:{selectedDate:today,recommendedDate:today,writeEnabled:true,myAppointment:active,cancelledAppointments:[],operationCounts:{cancelCount:0,modifyCount:0},dailySchedule:[{...active,isMine:true,booked:true}],makeupArtists:[{id:'t1',name:'小贝老师'}],teams:[{id:'g1',name:'星河一团'}],defaults:{},rules:{stepMinutes:10,durationMinutes:20,leadMinutes:20,cancelLimit:2,modifyLimit:3}}}}))
  await page.goto('/booking')
  await expect(page.getByRole('heading',{name:'今天',exact:true})).toBeVisible()
  await expect(page.locator('.schedule-person b')).toHaveText('小贝老师')
  await expect(page.locator('.schedule-person small')).toHaveText('玲玲 · 星河一团')
  await expect(page.locator('.appointment-card .time-display')).toHaveText('13:30')
  await expect(page.locator('.appointment-details')).toBeVisible()
  await expect(page.locator('.appointment-time .attendance-badge')).toHaveText('迟到')
  await expect(page.locator('.appointment-card').getByText('签到状态',{exact:true})).toHaveCount(0)
  await expect(page.getByText('已预约',{exact:true})).toHaveCount(0)
  await page.getByRole('button',{name:'打开账号菜单'}).click()
  await expect(page.getByRole('dialog',{name:'退出登录'})).toBeVisible()
})

test('administrator range filtering, total, pagination, export and send-card picker',async({page})=>{
  const appointmentQueries:string[]=[]
  page.on('request',request=>{if (request.url().includes('/api/v1/admin/appointments?')&&request.method()==='GET')appointmentQueries.push(request.url())})
  await mockAdmin(page)
  await page.goto('/admin')
  await expect(page.getByRole('navigation',{name:'预约日期'})).toBeVisible()
  await expect(page.getByLabel('开始日期')).toHaveCount(0)
  await page.getByRole('button',{name:'筛选预约记录'}).click()
  const currentDate=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(new Date())
  await expect(page.getByLabel('开始日期')).toContainText(currentDate)
  await expect(page.getByLabel('截止日期')).toContainText(currentDate)
  await expect(page.getByText('共 31 条记录')).toBeVisible()
  await expect(page.getByText('全部签到状态')).toBeVisible()
  await page.getByRole('button',{name:'近7天'}).click()
  await page.getByRole('button',{name:'查询'}).click()
  await expect(page.getByLabel('开始日期')).toHaveCount(0)
  await expect(page.locator('.date-tabs button.active')).toHaveCount(0)
  await expect.poll(()=>appointmentQueries.at(-1)??'').toContain('startDate=')
  await page.getByRole('navigation',{name:'预约日期'}).getByRole('button',{name:/今天/}).click()
  await expect.poll(()=>appointmentQueries.at(-1)??'').toContain('date=')
  await expect(page.locator('.overlap-badge:visible')).toHaveText('时间重叠')
  await expect(page.getByRole('button',{name:'上一页'})).toBeDisabled()
  await expect(page.getByRole('button',{name:'下一页'})).toBeEnabled()
  if((page.viewportSize()?.width??0)<=720)await expect(page.locator('.mobile-record-date').first()).toHaveText('09-07')
  await page.getByRole('button',{name:'导出预约数据'}).click()
  const exportSheet=page.getByRole('dialog',{name:'导出数据'})
  await expect(exportSheet).toContainText('时间区间')
  await expect(exportSheet).toContainText('全部')
  const download=page.waitForEvent('download')
  await exportSheet.getByRole('button',{name:'确认导出'}).click()
  expect((await download).suggestedFilename()).toBe('records.xlsx')
  await page.getByRole('button',{name:'发送钉钉群卡片'}).click()
  const sheet=page.getByRole('dialog',{name:'钉钉群卡片'})
  await expect(sheet.getByRole('button',{name:/今天/})).toBeVisible()
  await expect(sheet.getByRole('button',{name:/明天/})).toBeVisible()
  await expect(sheet.getByRole('button',{name:'确认发送'})).toBeEnabled()
  await sheet.getByRole('button',{name:/明天/}).click()
  await expect(sheet.getByRole('button',{name:'刷新卡片'})).toBeVisible()
})

test('range mode leaves card and proxy dates unselected until explicitly chosen',async({page})=>{
  await mockAdmin(page)
  await page.goto('/admin')
  await page.getByRole('button',{name:'筛选预约记录'}).click()
  await page.getByRole('button',{name:'昨天'}).click()
  await page.getByRole('button',{name:'查询'}).click()
  await page.getByRole('button',{name:'发送钉钉群卡片'}).click()
  let sheet=page.getByRole('dialog',{name:'钉钉群卡片'})
  await expect(sheet.locator('.card-date-options button.active')).toHaveCount(0)
  await expect(sheet.getByRole('button',{name:'确认发送'})).toBeDisabled()
  await sheet.getByRole('button',{name:'关闭'}).click()
  await page.locator('button:visible').filter({hasText:/^代预约$/}).click()
  await expect(page.getByText('请先选择预约日期')).toBeVisible()
  await expect(page.getByRole('button',{name:'确认代预约'})).toBeDisabled()
  await page.locator('.admin-date-choice').getByRole('button',{name:/今天/}).click()
  await page.getByRole('combobox',{name:'化妆师'}).click()
  await page.getByRole('option',{name:'小贝老师'}).click()
  await expect(page.getByRole('listbox',{name:'小时'})).toBeVisible()
  await expect(page.getByRole('listbox',{name:'分钟'})).toBeVisible()
})

test('custom filters remain mutually exclusive and admin avatar confirms logout',async({page})=>{
  await mockAdmin(page)
  await page.goto('/admin')
  await page.getByRole('button',{name:'筛选预约记录'}).click()
  const streamer=page.getByRole('combobox',{name:'主播筛选'}),makeupArtist=page.getByRole('combobox',{name:'化妆师筛选'})
  await streamer.click();await makeupArtist.click()
  await expect(streamer).toHaveAttribute('aria-expanded','false')
  await expect(makeupArtist).toHaveAttribute('aria-expanded','true')
  await page.getByRole('button',{name:'打开账号菜单'}).click()
  await expect(page.getByRole('dialog',{name:'退出登录'})).toBeVisible()
})

test('analytics exposes the expanded summary, trends and three BI rankings',async({page})=>{
  await mockAdmin(page)
  await page.goto('/admin')
  await page.locator('button:visible').filter({hasText:/^统计$/}).click()
  await expect(page.getByRole('heading',{name:'数据面板'})).toBeVisible()
  for(const label of ['预约','有效','签到','取消','迟到','未到','修改次数','取消次数','平均提前','平均迟到'])await expect(page.getByText(label,{exact:true}).first()).toBeVisible()
  await expect(page.getByRole('heading',{name:'有效预约'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'签到情况'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'每日趋势'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'BI 主播'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'BI 化妆师'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'BI 团播组'})).toBeVisible()
  await expect(page.getByText('50%',{exact:true})).toBeVisible()
  await expect(page.getByText('小贝老师',{exact:true})).toBeVisible()
  await expect(page.getByText('星河一团',{exact:true})).toBeVisible()
})

test('settings use first character avatars, counts and icon expanders',async({page})=>{
  await mockAdmin(page)
  await page.goto('/admin')
  await page.locator('button:visible').filter({hasText:/^设置$/}).click()
  const makeupCard=page.locator('.setting-card').filter({has:page.getByRole('heading',{name:'化妆师',exact:true})})
  await expect(makeupCard.locator('img.mini-avatar').first()).toHaveAttribute('src',/\.webp$/)
  await expect(makeupCard).toContainText('启用2/2')
  await expect(page.getByText('休息中···',{exact:true})).toBeVisible()
  await expect(page.getByText('已启用',{exact:true})).toHaveCount(0)
  await expect(page.getByText(/已停用/)).toHaveCount(1)
  await expect(page.getByRole('button',{name:'编辑停用测试团'})).toBeVisible()
  await expect(page.getByText('未绑定钉钉',{exact:false})).toHaveCount(0)
  const streamerCard=page.locator('.setting-card').filter({has:page.getByRole('heading',{name:'主播',exact:true})})
  await expect(streamerCard.locator('li')).toHaveCount(5)
  await expect(streamerCard).toContainText('启用6/6')
  await streamerCard.getByRole('button',{name:'展开 1 项'}).click()
  await expect(streamerCard.locator('li')).toHaveCount(6)
  await expect(streamerCard.getByRole('button',{name:'收起'})).toBeVisible()
})

test('makeup artist has one combined editor and unchanged save is silent',async({page})=>{
  const resourceUpdates:any[]=[],accountUpdates:any[]=[]
  page.on('request',request=>{if(request.url().endsWith('/api/v1/admin/makeup-artists/t1')&&request.method()==='PATCH')resourceUpdates.push(request.postDataJSON());if(request.url().endsWith('/api/v1/admin/accounts/m1')&&request.method()==='PATCH')accountUpdates.push(request.postDataJSON())})
  await mockAdmin(page)
  await page.route('**/api/v1/admin/makeup-artists/t1',r=>r.fulfill({json:{success:true,data:{}}}))
  await page.route('**/api/v1/admin/accounts/m1',r=>r.fulfill({json:{success:true,data:{}}}))
  await page.goto('/admin')
  await page.locator('button:visible').filter({hasText:/^设置$/}).click()
  const card=page.locator('.setting-card').filter({has:page.getByRole('heading',{name:'化妆师',exact:true})}),row=card.locator('li').first()
  await expect(row.getByRole('button')).toHaveCount(1)
  await row.getByRole('button',{name:'编辑小贝老师'}).click()
  let sheet=page.getByRole('dialog',{name:'小贝老师',exact:true})
  await expect(sheet).toContainText('最近上线：')
  await expect(sheet.getByText('排班与资源')).toHaveCount(0)
  await sheet.getByLabel('昵称').fill(' 小贝老师 ')
  await expect(sheet.getByRole('button',{name:'确定'})).toBeVisible()
  await sheet.getByRole('button',{name:'确定'}).click()
  await expect(sheet).toHaveCount(0)
  expect(resourceUpdates).toHaveLength(0);expect(accountUpdates).toHaveLength(0)
  await row.getByRole('button',{name:'编辑小贝老师'}).click()
  sheet=page.getByRole('dialog',{name:'小贝老师',exact:true})
  await sheet.getByRole('combobox',{name:'上班时间'}).click()
  await page.getByRole('option',{name:'09:00',exact:true}).click()
  await sheet.getByRole('button',{name:'保存'}).click()
  await expect.poll(()=>resourceUpdates.length).toBe(1)
  expect(resourceUpdates[0].workStart).toBe('09:00');expect(accountUpdates).toHaveLength(0)
  await expect(page.locator('.app-toast-success')).toContainText('账号已保存')
})

test('account creation uses on-demand DingTalk options and password actions are exclusive',async({page})=>{
  const created:any[]=[],updated:any[]=[]
  page.on('request',request=>{if(request.url().endsWith('/api/v1/admin/accounts')&&request.method()==='POST')created.push(request.postDataJSON());if(request.url().endsWith('/api/v1/admin/accounts/s2')&&request.method()==='PATCH')updated.push(request.postDataJSON())})
  const {accountRows}=await mockAdmin(page)
  await page.route('**/api/v1/admin/accounts/s2/assign-password',r=>{const account=accountRows.find(item=>item.id==='s2');account.username='JB2609074543';return r.fulfill({json:{success:true,data:{username:'JB2609074543',password:'123456'}}})})
  await page.route('**/api/v1/admin/accounts/s2/revoke-password',r=>{const account=accountRows.find(item=>item.id==='s2');delete account.username;return r.fulfill({json:{success:true,data:null}})})
  await page.route('**/api/v1/admin/accounts/s2',r=>r.fulfill({json:{success:true,data:{}}}))
  await page.goto('/admin')
  await page.locator('button:visible').filter({hasText:/^设置$/}).click()
  await expect(page.locator('.admin-user')).toContainText('超管 · Admin')
  await page.getByRole('button',{name:'添加主播'}).click()
  const createSheet=page.getByRole('dialog',{name:'添加 主播'})
  await expect(createSheet.getByText('账号启用',{exact:true})).toBeVisible()
  await expect(createSheet.getByText('在岗出勤',{exact:true})).toBeVisible()
  await expect(createSheet.getByRole('combobox',{name:'角色'})).toHaveCount(0)
  await expect(createSheet.getByRole('listbox',{name:'钉钉员工选项'})).toHaveCount(0)
  await createSheet.getByRole('button',{name:'选择钉钉人员'}).click()
  await expect(createSheet.getByRole('listbox',{name:'钉钉员工选项'})).toBeVisible()
  await createSheet.getByRole('button',{name:'搜索人员'}).click()
  await createSheet.getByLabel('搜索钉钉员工').fill('张三')
  await createSheet.getByRole('option',{name:/张三.*user123456/}).click()
  await expect(createSheet.getByPlaceholder('系统内显示的昵称')).toHaveValue('张三')
  await createSheet.getByRole('button',{name:'添加'}).click()
  await expect.poll(()=>created.length).toBe(1)
  await expect(createSheet).toHaveCount(0)
  expect(created[0]).toEqual({dingTalkUserId:'user123456',dingTalkUsername:'张三',nickname:'张三',role:'STREAMER',active:true,attending:true,canModifyAppointments:false,canCancelAppointments:false,canCreateAppointments:false})

  await page.getByRole('button',{name:'添加系统人员'}).click()
  const adminSheet=page.getByRole('dialog',{name:'添加 观察员'})
  await expect(adminSheet.getByRole('combobox',{name:'角色'})).toBeVisible()
  await expect(adminSheet.getByText('账号启用',{exact:true})).toBeVisible()
  await expect(adminSheet.getByText('代预约',{exact:true})).toHaveCount(0)
  await adminSheet.getByRole('combobox',{name:'角色'}).click()
  await page.getByRole('option',{name:'运营'}).click()
  const operatorSheet=page.getByRole('dialog',{name:'添加 运营'})
  await expect(operatorSheet).toBeVisible()
  await expect(operatorSheet.getByText('账号启用',{exact:true})).toBeVisible()
  await expect(operatorSheet.getByText('允许修改',{exact:true})).toBeVisible()
  await expect(operatorSheet.getByText('允许取消',{exact:true})).toBeVisible()
  await expect(operatorSheet.getByText('代预约',{exact:true})).toBeVisible()
  await operatorSheet.getByRole('button',{name:'关闭'}).click()

  await page.getByRole('button',{name:'添加化妆师'}).click()
  const makeupSheet=page.getByRole('dialog',{name:'添加 化妆师'})
  await expect(makeupSheet.getByText('账号启用',{exact:true})).toBeVisible()
  await expect(makeupSheet.getByText('在岗出勤',{exact:true})).toBeVisible()
  await expect(makeupSheet.getByText('代预约',{exact:true})).toBeVisible()
  await expect(makeupSheet.getByText('排班启用',{exact:true})).toBeVisible()
  await makeupSheet.getByRole('button',{name:'关闭'}).click()

  await page.getByRole('button',{name:'管理主播2'}).click()
  const editSheet=page.getByRole('dialog',{name:'主播2',exact:true})
  await expect(editSheet.getByText('钉钉身份创建后永久不可修改')).toHaveCount(0)
  await editSheet.getByRole('combobox',{name:'角色'}).click()
  await expect(page.getByRole('listbox',{name:'角色'}).getByRole('option').allTextContents()).resolves.toEqual(['主播','化妆师','运营','观察员'])
  await page.getByRole('option',{name:'主播'}).click()
  await expect(editSheet.getByRole('button',{name:'回收密码'})).toHaveCount(0)
  await editSheet.getByRole('button',{name:'分配密码'}).click()
  await expect(editSheet.getByText('JB2609074543')).toBeVisible()
  await expect(editSheet.getByText('123456',{exact:true})).toBeVisible()
  await expect(editSheet.getByRole('button',{name:'分配密码'})).toHaveCount(0)
  await editSheet.getByRole('button',{name:'回收密码'}).click()
  const revokeSheet=page.getByRole('dialog',{name:'确认回收密码'})
  await expect(revokeSheet).toContainText('回收后仅钉钉登录，账号密码登录需重新分配')
  await revokeSheet.getByRole('button',{name:'确认回收'}).click()
  await editSheet.getByRole('combobox',{name:'角色'}).click()
  await page.getByRole('option',{name:'化妆师'}).click()
  await editSheet.getByRole('button',{name:'保存'}).click()
  await expect.poll(()=>updated.length).toBe(1)
  expect(updated[0].role).toBe('MAKEUP')
})

test('observer can filter and read rules but cannot export',async({page})=>{
  await mockAdmin(page,'OBSERVER')
  await page.goto('/admin')
  await expect(page.getByRole('button',{name:'查看预约规则'})).toBeVisible()
  await expect(page.getByRole('button',{name:'导出预约数据'})).toHaveCount(0)
  await expect(page.getByLabel('签到状态筛选')).toHaveCount(0)
  await page.getByRole('button',{name:'筛选预约记录'}).click()
  await expect(page.getByLabel('签到状态筛选')).toBeVisible()
  if((page.viewportSize()?.width??0)<=720){const nav=page.getByRole('navigation',{name:'管理端导航'});await expect(nav.getByRole('button')).toHaveCount(2)}
})

test('operator cannot add or edit operator accounts',async({page})=>{
  await mockAdmin(page,'OPERATOR')
  await page.goto('/admin')
  await page.locator('button:visible').filter({hasText:/^设置$/}).click()
  const systemCard=page.locator('.setting-card').filter({has:page.getByRole('heading',{name:'系统人员',exact:true})})
  await expect(systemCard.getByRole('button',{name:'管理运营一号'})).toHaveCount(0)
  await page.getByRole('button',{name:'添加系统人员'}).click()
  const sheet=page.getByRole('dialog',{name:'添加 观察员'})
  await sheet.getByRole('combobox',{name:'角色'}).click()
  await expect(page.getByRole('option',{name:'运营'})).toHaveCount(0)
})

test('local settings rows switch to the selected test account',async({page})=>{
  let switchedTo=''
  await mockAdmin(page)
  await page.route('**/api/v1/auth/mock-login',async r=>{switchedTo=r.request().postDataJSON().userId;await r.fulfill({json:{success:true,data:{userId:switchedTo,nickname:'切换账号',role:'OBSERVER',canCreateAppointments:false,csrfToken:'next'}}})})
  await page.goto('/admin')
  await page.locator('button:visible').filter({hasText:/^设置$/}).click()
  const streamerCard=page.locator('.setting-card').filter({has:page.getByRole('heading',{name:'主播',exact:true})})
  await streamerCard.locator('li').first().click()
  await expect.poll(()=>switchedTo).toBe('streamer01')
})

test('duplicate nickname and team name show specific prompts',async({page})=>{
  let accountCreates=0
  await mockAdmin(page)
  await page.route('**/api/v1/admin/accounts',async r=>{
    if(r.request().method()==='POST'){accountCreates++;await r.fulfill({status:409,json:{success:false,error:{code:'NICKNAME_EXISTS',message:'昵称已存在，请使用其他昵称。'}}})}
    else await r.fallback()
  })
  await page.route('**/api/v1/admin/teams/g2',r=>r.fulfill({status:409,json:{success:false,error:{code:'TEAM_NAME_EXISTS',message:'团队名称已存在，请使用其他名称。'}}}))
  await page.goto('/admin')
  await page.locator('button:visible').filter({hasText:/^设置$/}).click()
  await page.getByRole('button',{name:'添加主播'}).click()
  let sheet=page.getByRole('dialog',{name:'添加 主播'})
  await sheet.getByRole('button',{name:'选择钉钉人员'}).click()
  await sheet.getByRole('option',{name:/张三.*user123456/}).click()
  await sheet.getByPlaceholder('系统内显示的昵称').fill(' Admin ')
  await sheet.getByRole('button',{name:'添加'}).click()
  await expect(page.locator('.app-toast-warning')).toContainText('昵称已存在，请使用其他昵称')
  expect(accountCreates).toBe(0)
  await sheet.getByRole('button',{name:'关闭'}).click()
  await page.getByRole('button',{name:'编辑停用测试团'}).click()
  sheet=page.getByRole('dialog',{name:'停用测试团'})
  await sheet.getByLabel('名称').fill('星河一团')
  await sheet.getByRole('button',{name:'保存'}).click()
  await expect(page.locator('.app-toast-warning')).toContainText('团队名称已存在，请使用其他名称')
})

test('appointment detail hides false overlap and shows true overlap',async({page})=>{
  let conflict=false
  await mockAdmin(page)
  await page.route('**/api/v1/admin/appointments/a1',r=>r.fulfill({json:{success:true,data:{...appointment,bookingNumber:'090810001-streamer01',conflictOverride:conflict}}}))
  await page.goto('/admin')
  const openDetail=(page.viewportSize()?.width??0)<=720
    ? page.locator('.mobile-admin-list > button:visible').first()
    : page.getByRole('button',{name:'查看预约详情'}).first()
  await openDetail.click()
  let sheet=page.getByRole('dialog',{name:'预约详情'})
  await expect(sheet.getByText('时间重叠',{exact:true})).toHaveCount(0)
  await sheet.getByRole('button',{name:'关闭'}).click()
  conflict=true
  await openDetail.click()
  sheet=page.getByRole('dialog',{name:'预约详情'})
  await expect(sheet.getByText('时间重叠',{exact:true})).toBeVisible()
})

test('makeup permission hides create entry and the whole mobile navigation',async({page})=>{
  await mockAdmin(page)
  await page.route('**/api/v1/me',r=>r.fulfill({json:{success:true,data:{userId:'makeup01',nickname:'小贝老师',role:'MAKEUP',makeupArtistId:'t1',canModifyAppointments:false,canCancelAppointments:false,canCreateAppointments:false,csrfToken:'csrf'}}}))
  await page.goto('/admin')
  await expect(page.getByText('代预约',{exact:true})).toHaveCount(0)
  await expect(page.getByRole('navigation',{name:'管理端导航'})).toHaveCount(0)
})

test('disabled schedule locks controls and requires weekdays when re-enabled',async({page})=>{
  await mockAdmin(page)
  await page.route('**/api/v1/admin/makeup-artists',r=>r.fulfill({json:{success:true,data:[{id:'t1',name:'小贝老师',workDays:[],workStart:'08:00',workEnd:'20:00',scheduleEnabled:false,active:true,attending:true,version:0}]}}))
  await page.goto('/admin')
  await page.locator('button:visible').filter({hasText:/^设置$/}).click()
  await page.getByRole('button',{name:'编辑小贝老师'}).click()
  const sheet=page.getByRole('dialog',{name:'小贝老师',exact:true})
  await expect(sheet.getByRole('button',{name:'周一'})).toBeDisabled()
  await expect(sheet.getByRole('combobox',{name:'上班时间'})).toBeDisabled()
  await sheet.getByText('排班启用',{exact:true}).locator('..').getByRole('button').click()
  await expect(sheet.getByRole('button',{name:'周一'})).toBeEnabled()
  await sheet.getByRole('button',{name:'保存'}).click()
  await expect(page.locator('.app-toast-warning')).toContainText('请至少选择一个工作日')
})

test('forbidden employee is isolated',async({page})=>{
  await page.goto('/forbidden')
  await expect(page.getByRole('heading',{name:'暂时没有使用权限'})).toBeVisible()
})

